language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t michalburdzy/someapp -f Dockerfile.dev .

script:
  - docker run -e CI=true michalburdzy/someapp npm run test
